deployment:
  replicas: 1
  strategy:
    type: RollingUpdate
  serviceAccount: stackrox-relay
  imagePullPolicy: Always
  ports:
  - name: http
    containerPort: 8080
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 100Mi
  containerSecurityContext:
    privileged: false
    allowPrivilegeEscalation: false
    runAsUser: 1001
    seccompProfile:
      type: RuntimeDefault
    runAsNonRoot: true
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL
  readinessProbe:
    httpGet:
      path: /healthz
      port: 8080
    initialDelaySeconds: 3
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  livenessProbe:
    httpGet:
      path: /healthz
      port: 8080
    initialDelaySeconds: 10
    periodSeconds: 15
    timeoutSeconds: 5
    failureThreshold: 3

  image:
    repository: ghcr.io/forma22-agency/stackrox-relay-service
    tag: c666371b7a6ebba7ec87bcc715c1ed171108aeb0

# Use plain text values for the app secrets
configmap:
  GH_OWNER: "forma22-agency"
  # Repo where replay need access to dispatch events
  GITHUB_API_VERSION: "2022-11-28"
  EVENT_TYPE: "stackrox_copa"
  # Optional: allow multi-repo mode by GitHub repository topics
  # Comma-separated list of topics that must be present on target repo.
  # If empty, any repo is allowed (subject to credentials).
  GH_ALLOWED_TOPICS: "stackrox-copa"
  # one of: any | all
  GH_ALLOWED_TOPICS_MODE: "any"
  # Optional: random secret for StackRox webhook
  ACS_WEBHOOK_SECRET: ""
  # optional, if you want to use a GitHub PAT token without a external secret
  GH_TOKEN: ""
  # optional, if you want to use a logging level
  LOG_LEVEL: "DEBUG"

# Use external secrets for the app secrets
externalSecrets:
  enabled: false
  name: stackrox-relay-service-secrets
  data:
    refreshInterval: 1h
    secretStoreRef:
      kind: ClusterSecretStore
      name: storage
    creationPolicy: Owner
    # Secrets #
    acsWebhookSecret:
      # if you want to store the ACS webhook secret in a secret store
      enabled: false
      parameters:
        remoteSecretKey: stackrox-relay-acs-webhook-secret
    token:
       # if you want to use a GitHub PAT token
      enabled: false
      parameters:
        name: stackrox-relay-gh-token
        remoteSecretKey: stackrox-relay-gh-token
    app:
      # if you want to use a GitHub App
      enabled: false
      parameters:
        githubAppID: 1234567890
        githubAppInstallationID: 1234567890
        remoteSecretKey: stackrox-relay-gh-app-pk

service:
  type: ClusterIP
  ports:
    name: http
    port: 80
    targetPort: 8080
