deployment:
  replicas: 1
  strategy:
    type: RollingUpdate
  serviceAccount: stackrox-relay
  imagePullPolicy: Always
  ports:
  - name: http
    containerPort: 8080
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 100Mi
  containerSecurityContext:
    privileged: false
    allowPrivilegeEscalation: false
    runAsUser: 1001
    seccompProfile:
      type: RuntimeDefault
    runAsNonRoot: true
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL
  readinessProbe:
    httpGet:
      path: /healthz
      port: 8080
    initialDelaySeconds: 3
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  livenessProbe:
    httpGet:
      path: /healthz
      port: 8080
    initialDelaySeconds: 10
    periodSeconds: 15
    timeoutSeconds: 5
    failureThreshold: 3

  image:
    repository: ghcr.io/igorgolm/stackrox-relay-service
    tag: 97daacacb665a52e38a21bddecd92a2aa83054df

configmap:
  GH_OWNER: "igorgolm"
  GH_REPO: "aws-cd-georgia-demo-app" # Repo where replay need access to dispatch events
  GITHUB_API_VERSION: "2022-11-28"
  EVENT_TYPE: "stackrox_copa"
  ACS_WEBHOOK_SECRET: "super-secret" # Random secret for StackRox webhook
  GH_TOKEN: "" # GitHub PAT token

service:
  type: ClusterIP
  ports:
    name: http
    port: 80
    targetPort: 8080