apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels:
  {{- include "stackrox-relay-service.labels" . | nindent 4 }}
data:
  GH_OWNER: "{{ .Values.configmap.GH_OWNER }}"
  GH_ALLOWED_TOPICS: "{{ .Values.configmap.GH_ALLOWED_TOPICS }}"
  GH_ALLOWED_TOPICS_MODE: "{{ .Values.configmap.GH_ALLOWED_TOPICS_MODE }}"
  GITHUB_API_VERSION: "{{ .Values.configmap.GITHUB_API_VERSION }}"
  EVENT_TYPE: "{{ .Values.configmap.EVENT_TYPE }}"
  {{ if .Values.configmap.RELAY_DEDUP_ENABLED }}
  RELAY_DEDUP_ENABLED: "{{ .Values.configmap.RELAY_DEDUP_ENABLED }}"
  RELAY_DEDUP_TTL_SECONDS: "{{ .Values.configmap.RELAY_DEDUP_TTL_SECONDS }}"
  REDIS_URL: "{{ .Values.configmap.REDIS_URL }}"
  {{ end }}
  {{ if .Values.configmap.ACS_WEBHOOK_SECRET }}
  ACS_WEBHOOK_SECRET: "{{ .Values.configmap.ACS_WEBHOOK_SECRET }}"
  {{ end }}
  {{ if .Values.configmap.GH_TOKEN }}
  GH_TOKEN: "{{ .Values.configmap.GH_TOKEN }}"
  {{ end }}