name: Build and push image

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'app/**'
      - 'requirements.txt'
  pull_request:
    branches:
      - main
    types: [ opened, synchronize, reopened ]
    paths:
      - 'Dockerfile'
      - 'app/**'
      - 'requirements.txt'

jobs:
  build_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v5

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      if: github.base_ref != 'main'
      with:
        push: false
        platforms: linux/amd64,linux/arm64
        tags: ghcr.io/forma22-agency/stackrox-relay-service:${{ github.sha }}

    - name: Build and push
      uses: docker/build-push-action@v6
      if: github.base_ref == 'main'
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ghcr.io/forma22-agency/stackrox-relay-service:${{ github.sha }}