name: Release helm chart

on:
  push:
    branches:
      - main
    paths:
      - 'helm-chart/**'

jobs:
  release_helm_chart:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.7.0
      env:
        charts_dir: helm-chart/
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

    - name: Run helm-docs
      uses: losisin/helm-docs-github-action@v1
      with:
        git-push: true
        git-commit-message: "chore: update Helm documentation [skip ci]"
        chart-search-root: helm-chart/